sudo: false
language: php

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache
    - includes/lib/
    - vendor/

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=trunk RUN_PHPCS=1

install:
  - composer install --prefer-dist --no-suggest
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      ./vendor/bin/phpcs
    fi

after_script:
  - if [ $CODECLIMATE_REPO_TOKEN ]; then ./vendor/bin/test-reporter; fi;


